stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

  script:
    - ssh $SSH_USER@$SERVER_IP "
        cd devops-docker-terraform-project &&
        git pull &&
        docker stop devops-container || true &&
        docker rm devops-container || true &&
        docker build -t devops-demo -f docker/Dockerfile . &&
        docker run -d -p 80:5000 --name devops-container devops-demo
      "
